# Generated by Django 4.2.10 on 2024-09-15 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veggieapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='post',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
