# Generated by Django 4.2.10 on 2024-09-14 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veggieapp', '0002_post_date_posted_post_item_description_post_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggieapp.user'),
        ),
    ]
