# Generated by Django 4.2.10 on 2024-09-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggieapp', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_request',
            field=models.BooleanField(default=False),
        ),
    ]
