# Generated by Django 4.2.10 on 2024-09-15 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veggieapp', '0004_post_is_open_post_is_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_open',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_request',
        ),
    ]
