# Generated by Django 4.2.10 on 2024-09-15 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veggieapp', '0005_remove_post_is_open_remove_post_is_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_posted',
        ),
    ]
