# Generated by Django 4.2.10 on 2024-09-15 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veggieapp', '0005_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='post',
            field=models.ForeignKey(default='anonymous', on_delete=django.db.models.deletion.CASCADE, to='veggieapp.post'),
        ),
    ]
