# Generated by Django 4.2.10 on 2024-09-15 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veggieapp', '0006_offer_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='post',
        ),
    ]
